### ISSUE TITLE
Discovery Document CDS endpoint names

### ISSUE THREAD

**Issue by wcai-biza** [datarightplus/datarightplus-redocly#10] opened 2024-09-10 06:38 UTC
The endpoint names in Discovery Document do not match the `operationId` in CDS spec. For example, `operationId` for "Get Account Balance" endpoint is "getBalance" in CDS spec, but it is "getBankingBalance" in Discovery Document.

I understand that it has to be named as "getBankingBalance" to avoid confusion/conflict with Energy API, but I feel like it is still preferable to stick with CDS spec `operationId`.

Could we introduce industry sections in Discovery Document? e.g. `schema.cds.endpoint.banking.getBalance`?

**Comment by perlboy** [comment] 2024-09-14 03:24
Introducing industry sections to avoid collision in discovery document permits `operationId` collisions in the actual operation definitions which is not desirable.

With respect to `operationId` names, the reasoning here relates to ensuring DataRight+ specifications are a closed loop, even if they restate upstream specifications. In this respect, the `operationId` used, which also rename from original upstream, are the same as [DataRight+ Redocly](https://datarightplus.github.io/datarightplus-redocly) for these endpoints. The `cds` scheme from the discovery specification references the [DataRight+: Australian CDR Profile](https://datarightplus.github.io/datarightplus-cdr-profile/draft-authors-datarightplus-cdr-profile.html) which uses [DataRight+ Redocly](https://datarightplus.github.io/datarightplus-redocly). 

_Maybe_ an alternate would be to align our redocly with the upstream but as more sectors (that may not be in CDS at all but may be in the Redocly spec) are added the problem becomes more and more obvious.

On this basis this is _not a bug_ and I've marked it as won't fix.

**Closed as completed by perlboy** 2024-09-14 03:24 UTC
Labels: bug, wontfix
